### ISSUE TITLE
Minimum deployment target

### ISSUE THREAD

**Issue by sochalewski** [recruit-lifestyle/Smile-Lock#1]
Why minimum deployment target set in .podspec is as high as 9.0? I believe it would work well with iOS 8.0.

**Comment by liu044100** [comment]
Hi, @sochalewski.

You are right, but some layout code that use the new API 'NSLayoutAnchor' in iOS9 (because I am so lazy and want to use the simple API…😬), it is not difficult change these code to 'NSLayoutConstraint', if I have time, I will change it make it more compatible, or you can change it by yourself and pull a request.

**Comment by liu044100** [comment]
One more thing that the storyboard is using the iOS9 new feature - 'UIStackView' in 'PasswordContainerView', it may be a little convoluted to change it for iOS7&8 compatibility.
