### ISSUE TITLE
Transparent background color for password input view

### ISSUE THREAD

**Issue by Conrad-m-wise** [recruit-lifestyle/Smile-Lock#8]
Hi,

I love this UI component. I am using it in a app i am developing and i have a question regarding customising the look and feel.

Basically i want the password input views to have a solid border color (white) with a transparent background color. 

I tried setting sit up with the following settings:

 //customize password UI
passwordContainerView?.tintColor = UIColor(hexString: "#959595")       passwordContainerView?.highlightedColor =  UIColor(hexString:"#50C5D7")

passwordContainerView?.passwordInputViews.forEach({ (view:PasswordInputView) in
                view.circleBackgroundColor = UIColor.ClearColor()
                view.borderColor = UIColor(hexString: "#959595") ?? UIColor.whiteColor()
                view.highlightBackgroundColor = UIColor(hexString:"#50C5D7") ?? UIColor.blackColor()
                view.textColor = UIColor.whiteColor()
                view.highlightTextColor = UIColor.whiteColor()
})

But the password input field do not have a clear background color but instead have the border color is this correct? There is no way to set them up separately from each other?

**Comment by liu044100** [comment]
Hi @Conrad-m-wise,  thanks for you love this component.  :-)

Sorry for that currently, there is no elegant way to use a clear background color.

As shown on figure below, you can see that below the `circleView` of `PasswordInputView`(the white color view below the number) has the gray color view that is the root view of `PasswordInputView`.

![screen shot 2016-08-05 at 22 39 01](https://cloud.githubusercontent.com/assets/3689476/17438401/94f027bc-5b5d-11e6-94a6-ed0d2e4b614d.png)

So it does not work, because the root view is not clear color.

I recommend you use the blur effect, like [BlurPasswordLoginViewController](https://github.com/recruit-lifestyle/Smile-Lock/blob/master/SmileLock-Example/SmileLock-Example/BlurPasswordLoginViewController.swift), how about it?

**Comment by liu044100** [comment]
I have one more idea as shown below. 💡

```swift
        //customize password UI
        self.passwordContainerView.tintColor = UIColor.color(.TextColor)
        self.passwordContainerView.highlightedColor = UIColor.color(.Blue)
        
        self.passwordContainerView.passwordInputViews.forEach {
            $0.borderColor = UIColor.clearColor()
            $0.circleBackgroundColor = UIColor.clearColor()
        }
```

But it will lose the circle border when the button on normal state.
![simulator screen shot 5 aug 2016 23 24 24](https://cloud.githubusercontent.com/assets/3689476/17439628/f39e16e2-5b63-11e6-8e0a-37a303881d8e.png)

**Comment by Conrad-m-wise** [comment]
Hi,

Yeah i tried the second option but indeed you loose the border. I will check-out the BlurPasswordLoginViewController set up and see if it fits my need. Thanks. You will hear back from me.
